### PR TITLE
remove license file

### PR DESCRIPTION
**Pull request by olowoshiai**

### CODE REVIEW

**Comment by TheIronMarx** [comment]
Why are we removing licenses?

**Comment by Alarson93** [comment]
I second Sam's question.
Having a license is quite important for public facing libraries.

**Comment by olowoshiai** [comment]
Removing the license files for our libraries & cocoapods was listed as one of our internal ios tasks.. I recall discussing this at one of our team meetings. But it seems like we wanna leave the files for specific projects @Alarson93 ?

**Comment by Janglinator** [comment]
Correct, but only for repositories that aren't externally available.  If they're on Github, they're public.

My assumption is that license files in those repos give others the right to use them if they somehow got ahold of them (clients, etc)

**Comment by TheIronMarx** [comment]
Everything open source needs a license.

**Comment by Alarson93** [comment]
We talked about this offline as well. I will mark the issue as closed.

**Pull request closed without merging**
